Repository boostcamp-2020/IssueTracker-29, pull requests merged in 2020-11, with the labels that each got.

#72 [FEAT] 헤더, 이슈 목록 화면 일부 레이아웃 구현
  client/.eslintrc.js
  client/.prettierrc.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/header/header.js
  client/src/components/issue/api.js
  client/src/components/issue/issue.js
  client/src/components/issue/issueItem.js
  client/src/components/login/index.js
  client/src/components/topbar/topbar.js
  client/util/config.js
  client/webpack.config.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: frontend

#75 [FEAT] FilterButton 리팩토링, 모달창 구현
  client/src/components/common/modal.js
  client/src/components/issue/issue.js
  client/src/components/issue/tapList.js
  client/src/components/topbar/filterButton.js
  client/src/components/topbar/topbar.js
Labels: frontend

#77 [FEAT] 필터링을 위한 탭 뷰 구현, 필터링 기능 일부 구현
  client/src/components/common/modal.js
  client/src/components/issuelist/api.js
  client/src/components/issuelist/tabList.js
  client/src/components/topbar/filterButton.js
  client/src/components/topbar/topbar.js
  server/middlewares/auth/token.js
  server/middlewares/user.js
  server/models/query.js
  server/routes/user.js
Labels: frontend

#78 [J009] issue 상세 페이지 일부 구현
  client/src/App.js
  client/src/components/common/api.js
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issuelist/issueHook.js
  client/src/components/issuelist/issuelist.js
  ecosystem.config.js
Labels: frontend

#81 [FEAT] 필터링 리스트 출력, 검색창 submit event 구현
  client/src/components/common/modal.js
  client/src/components/issuelist/tabList.js
  client/src/components/issuelist/tabListHook.js
  client/src/components/topbar/topbar.js
  server/middlewares/milestone.js
  server/models/query.js
  server/routes/milestone.js
  server/routes/user.js
Labels: frontend

#83 [J009] Issue 상세 페이지 side bar 일부 작업
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issueDetail/issueDetailHook.js
Labels: frontend

#86 [J009] issue 상세 페이지 관련 hook 설정 및 query 수정
  client/src/App.js
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issueDetail/issueDetailHeader.js
  client/src/components/issueDetail/issueDetailHook.js
  client/src/components/issueDetail/svgSettingsLogo.js
  server/models/query.js
Labels: frontend

#88 [J212] 필터링 조건 문서화, 충돌 해결
  client/src/components/common/filterCondition.js
  client/src/components/common/modal.js
  client/src/components/issuelist/issuelist.js
  client/src/components/issuelist/tabList.js
  client/src/components/topbar/filterButton.js
  client/src/components/topbar/topbar.js
Labels: frontend

#92 [J212] 필터링 사항에 대한 리다이렉트 라우터 구현
  client/src/components/common/context.js
  client/src/components/issuelist/context.js
  client/src/components/issuelist/issuelist.js
  client/src/components/issuelist/tabList.js
  client/src/components/topbar/filterButton.js
  client/src/components/topbar/topbar.js
Labels: frontend

#93 [J009] Issue 상세 페이지 comment 출력 및 세부 정보 출력
  client/src/components/common/commentItem.js
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issueDetail/issueDetailCommentInput.js
  client/src/components/issueDetail/issueDetailContent.js
  client/src/components/issueDetail/issueDetailHeader.js
  client/src/components/issueDetail/issueDetailHook.js
  client/src/components/issueDetail/issueDetailSideBar.js
  server/models/query.js
Labels: frontend

#98 [J212] 이슈 페이지로 넘어가지 않는 오류 수정, 필터링 기능 구현 완료
  client/src/components/issuelist/issuelist.js
  client/src/components/login/index.js
Labels: frontend

#100 [J009] issue 상세 페이지에서 출력되는 comment의 contents 마크다운 형식으로 출력
  client/package-lock.json
  client/package.json
  client/src/components/common/commentItem.js
  client/src/components/common/issueSideBar.js
  client/src/components/common/issueSideBarModal.js
  client/src/components/issueDetail/issueDetailHook.js
  client/src/components/issuelist/issuelist.js
  client/webpack.config.js
Labels: frontend

#102 [J212] 이슈 필터링 Submit event 방지, 기본 Condition 적용, OAuth 에러 해결
  client/src/components/issuelist/issuelist.js
  client/src/components/login/index.js
  client/src/components/topbar/topbar.js
  server/app.js
  server/middlewares/auth/passport.js
  server/models/query.js
  server/routes/user.js
Labels: backend, frontend

#103 [J212] 필터 조건 초기화 기능 구현, 로그인 후 리다이렉트되게 수정
  client/src/components/login/index.js
  client/src/components/topbar/topbar.js
  server/middlewares/auth/passport.js
  server/middlewares/auth/token.js
  server/routes/user.js
Labels: backend, frontend

#104 [J212] 사용자 DB 조회 관련 오류 해결, req.user에 접근할 수 없는 문제 해결
  server/app.js
  server/middlewares/auth/passport.js
  server/package-lock.json
  server/package.json
Labels: backend, bug

#105 [J212] 이슈 생성 시 user를 참조할 수 없는 오류 해결, query에 created_at이 추가되지 않은 문제 해결
  server/middlewares/auth/passport.js
  server/middlewares/auth/token.js
  server/middlewares/issue.js
  server/models/query.js
  server/routes/index.js
Labels: backend, bug

#108 [J009] issue 상세 페이지의 comment 생성 및 변경 기능 구현
  client/src/components/common/api.js
  client/src/components/common/commentItem.js
  client/src/components/header/header.js
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issueDetail/issueDetailCommentInput.js
  client/src/components/issueDetail/issueDetailHeader.js
  client/src/components/newIssue/contentContainer.js
Labels: frontend

#110 [J212] 라벨/마일스톤 공통 탭 구현, 새 마일스톤 생성 기능 구현
  client/src/components/labellist/labellist.js
  client/src/components/milestone/milestoneHook.js
  client/src/components/milestone/milestoneItem.js
  client/src/components/milestone/milestoneList.js
  client/src/components/newMilestone/newMilestone.js
  client/src/components/topbar/labelMilestoneTab.js
  client/src/components/topbar/topbar.js
  server/models/query.js
Labels: frontend

#112 [J212] 마일스톤 수정 기능 구현, 로그인 버튼 스타일 작업
  client/src/App.js
  client/src/components/MilestoneEditer/MilestoneEditer.js
  client/src/components/login/index.js
  client/src/components/milestone/milestoneHook.js
  client/src/components/milestone/milestoneItem.js
  client/src/components/milestone/milestoneList.js
  client/src/components/newMilestone/milestoneInputForm.js
  client/src/components/newMilestone/newMilestone.js
  client/src/components/topbar/labelMilestoneTab.js
  client/src/components/topbar/topbar.js
  server/models/query.js
Labels: frontend

#114 [J009] issue sidebar 모달창 작업
  client/src/components/common/commentItem.js
  client/src/components/common/issueSideBar.js
  client/src/components/common/issueSideBarHook.js
  client/src/components/common/issueSideBarModal.js
  client/src/components/common/sideBarItem.js
  client/src/components/common/svgSettingsLogo.js
  server/models/query.js
Labels: frontend

#117 [J212] 개발/배포 환경에 따른 config value 분리, 모달 리팩토링, 로그인/라벨/마일스톤 스타일 작업
  client/src/App.js
  client/src/components/MilestoneEditer/MilestoneEditer.js
  client/src/components/common/context.js
  client/src/components/common/icon/svgGithubIcon.js
  client/src/components/common/issueSideBar.js
  client/src/components/common/issueSideBarModal.js
  client/src/components/common/modal.js
  client/src/components/common/modalhook.js
  client/src/components/common/sideBarItem.js
  client/src/components/common/style/button.js
  client/src/components/common/style/labelcontainer.js
  client/src/components/common/svgSettingsLogo.js
  client/src/components/issuelist/issueHook.js
  client/src/components/issuelist/issuelist.js
  client/src/components/issuelist/tabList.js
  client/src/components/issuelist/tabListHook.js
  client/src/components/labellist/labelCreate.js
  client/src/components/labellist/labelEdit.js
  client/src/components/labellist/labelItemViewer.js
  client/src/components/login/index.js
  client/src/components/milestone/milestoneHook.js
  client/src/components/milestone/milestoneItem.js
  client/src/components/newMilestone/milestoneInputForm.js
  client/src/components/newMilestone/newMilestone.js
  client/src/components/topbar/filterButton.js
  client/src/components/topbar/topbar.js
  client/util/config.js
  server/config/index.js
  server/middlewares/auth/token.js
  server/routes/index.js
Labels: frontend

#120 [J009] issue 상세 페이지 styled-components 적용
  client/src/components/common/commentItem.js
  client/src/components/issueDetail/issueDetail.js
  client/src/components/issueDetail/issueDetailCommentInput.js
  client/src/components/issueDetail/issueDetailContent.js
  client/src/components/issueDetail/issueDetailHeader.js
  client/src/components/issueDetail/issueDetailHook.js
  ecosystem.config.js
  server/middlewares/user.js
  server/models/query.js
  server/routes/user.js
Labels: frontend
